### ISSUE TITLE
How to combine with SLAM map

### ISSUE THREAD

**Issue by guangjhaogu** [SICKAG/sick_lidar_localization#7]
HI, the map file of Sick LOC is .smap, how to combine with SLAM and navigation, because SLAM and navigation use .pgm, thanks

**Comment by michael1309** [comment]
Hello,

unlike a standard map, which may be stored in an image format such as "pgm", the localization software expects a contour map in SICK's internal "smap" format. The map is usually generated by the movement of the installed lidar in the AGV.
If you have the map and want to generate the "smap" map from it, I recommend to contact the SICK support.

You can find further information (also about the SICK Map Engineering Tool (SMET)) e.g. under these links:
* Map Creation: 
https://cdn.sick.com/media/familyoverview/5/55/155/familyOverview_Map-creation_g473155_en.pdf
or in general form in the manual:
* https://cdn.sick.com/media/docs/0/20/720/operating_instructions_operating_instructions_en_im0082720.pdf under section 6.4.2

Since this question is more of a general nature and therefore rather "off topic", we hereby close the ticket again and wish you good luck.
